[workspace]
members = ["proto-gen"]
exclude = ["examples/example-project", "examples/example-integration"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
proto-gen = { path = "../proto-gen" }
tempfile = "3.21"
tonic-prost-build = "0.14"

