[workspace]
members = ["proto-gen", "proto-gen-cli"]
exclude = ["examples/example-project"]

[workspace.dependencies]
clap = { version = "4.0", features = ["derive"] }
proto-gen = { path = "../proto-gen" }
tempfile = "3.3.0"
tonic-build = { version = "0.8.4", default-features = false, features = ["transport", "prost"] }
